#multipar configuration

#enable multipart uploads
spring.servlet.multipart.enabled=true

#max file size
spring.servlet.multipart.max-file-size= 300MB

#thresold after which file are writtento disk
spring.servlet.multipart.file-size-threshold=1KB